### PR TITLE
Add PHP 5.6 ius

### PR DESCRIPTION
**Pull request by jameshalsall**
This also contains the PHP 5.5 work from @dcole-inviqa in #48.

### CODE REVIEW

**Comment by andytson** [comment]
This cookbook is no longer supported

**Comment by andytson** [comment]
Also we don't use IUS for PHP anymore

**Comment by jameshalsall** [comment]
What is the preferred way of moving to PHP 5.6 on projects that are using this cookbook?

**Comment by andytson** [comment]
It can be replaced with the php cookbook's node['php']['packages'] array. See the seeds for how that's done. It shouldn't require much more than to update the php cookbook to one that supports it, and creating a chef role like that of the ones in the seeds https://github.com/inviqa/hem-seed-default/tree/master/tools/chef/roles

**Comment by jameshalsall** [comment]
Thanks Andy

**Pull request closed without merging**
